import Navbar from '../components/Navbar';
import MintButton from '../components/MintButton';
import styles from '../styles/NFTs.module.css';
import Image from 'next/image';

const nfts = () => (
  <>
    <Navbar />
    <section id="nfts" className={styles.nftsSection}>
      <h2 className={styles.nftsTitle}>Smart Sentinels NFTs</h2>
      <div className={styles.nftsMainDescription}>
        <p>
          Discover our exclusive NFT collections that power the Smart Sentinels ecosystem. Each NFT represents a stake in our AI-driven platform, unlocking rewards and unique utilities. Mint your NFT to become a stakeholder and participate in the future of decentralized AI.
        </p>
        <p>
          Our NFTs grant access to staking, governance, and special features within the Smart Sentinels network. Join the revolution and own a piece of the next generation of AI-powered blockchain technology!
        </p>
      </div>
      <div className={styles.nftsContainer}>
        <div className={styles.nftsDescription}>
          <h3 className={styles.nftSubtitle}>AI Audit Sentinel</h3>
          <p>
            The AI Audit Sentinel NFT unlocks access to revenue sharing from our active auditing agents. When the agent is performing audits, it is generating value—tokens are created as a result of its work and are distributed among all AI Audit Sentinel NFT holders. By owning this NFT, you directly benefit from the productivity of our AI-powered auditing system and share in the rewards generated by real, useful work on the blockchain.
          </p>
          <div className={styles.mintButtonWrapper}>
            <MintButton />
          </div>
        </div>
        <div className={styles.nftsMedia}>
          <div className={styles.nftCard}>
            <video
              className={styles.nftVideo}
              width="400"
              height="400"
              autoPlay
              loop
              muted
              playsInline
            >
              <source src="/nft-preview.mp4" type="video/mp4" />
              Your browser does not support the video tag.
            </video>
          </div>
        </div>
      </div>

      <div className={styles.upcomingWrapper}>
        <h2 className={styles.upcomingTitle}>Upcoming Collections</h2>
        <div className={styles.upcomingContainer}>
          <div className={styles.upcomingCard}>
            <img src="/collection1.png" alt="Collection 1" className={styles.upcomingImage} />
            <h3 className={styles.upcomingName}>Nvidia Powered Agents</h3>
            <p className={styles.upcomingDesc}>
              Acces to exclusive AI agents powered by Nvidia Orin devices. These agents will perform complex tasks and generating rewards for NFT holders.
            </p>
          </div>
          <div className={styles.upcomingCard}>
            <Image 
            src="/collection1.png"alt="Collection 1"
            width={180}
            height={180}
            className={styles.upcomingImage}/>
            <h3 className={styles.upcomingName}>Sentinel Legends</h3>
            <p className={styles.upcomingDesc}>
              Legendary Sentinels with rare traits and enhanced staking rewards. Only a select few will own these!
            </p>
          </div>
        </div>
      </div>
    </section>
  </>
);

export default nfts;