import React from 'react';
import styles from '../styles/Hero.module.css';
import Image from 'next/image';

const useBreakpoint = () => {
  const [bp, setBp] = React.useState('desktop');
  React.useEffect(() => {
    const check = () => {
      if (window.innerWidth <= 425) setBp('mobile');
      else if (window.innerWidth <= 1023) setBp('tablet');
      else setBp('desktop');
    };
    check();
    window.addEventListener('resize', check);
    return () => window.removeEventListener('resize', check);
  }, []);
  return bp;
};

const Hero = () => {
  const bp = useBreakpoint();

  return (
    <section id="home" className={styles.hero}>
      <div className={styles.heroMain}>
        <div className={styles.heroText}>
          <h1>Smart Sentinels</h1>
          <h6>Real work, Real Rewards</h6>
          <h2>Innovative Proof of Useful Work</h2>
          {(bp === 'mobile' || bp === 'tablet') && (
            <div className={styles.heroImage}>
              <Image
                src="/SmartSentinel.png"
                alt="AI Agent"
                width={800}
                height={800}
                className={styles.heroImg}
                priority
              />
            </div>
          )}
          <p>
            Unlock the Future with Smart Sentinels, where cutting-edge AI technology meets the decentralized world of cryptocurrency. Our AI Agents, running on the powerful Nvidia Jetson Orin Nano Super devices and powerful GPUs, generate tokens as they work, creating value and opportunities for our community.
          </p>
          <p>
            Become a Stakeholder by minting NFTs from our exclusive collections and share in the rewards generated by our AI Agents. Whether  Smart Contract audits, advanced AI-driven call centers, tech support, or agents working in the medical domain, Smart Sentinels is at the forefront of integrating AI and blockchain.
          </p>
        </div>
        {bp === 'desktop' && (
          <div className={styles.heroImage}>
            <Image
              src="/SmartSentinel.png"
              alt="AI Agent"
              width={800}
              height={800}
              className={styles.heroImg}
              priority
            />
          </div>
        )}
      </div>
      <div className={styles.expandedSection}>
        <div className={styles.expandedText}>
          <h2>How?</h2>
          <div className={styles.expandedImage}>
            <Image
              src="/howto.png"
              alt="How it works"
              width={400}
              height={200}
              className={styles.expandedImg}
            />
          </div>
          <p>
            Our AI Agents utilize advanced machine learning algorithms to analyze and optimize blockchain transactions, ensuring maximum efficiency and security. By leveraging the power of AI, we are able to provide unparalleled services in smart contract audits, AI-driven call centers, and tech support.
          </p>
        </div>
      </div>
    </section>
  );
};

export default Hero;