import React from 'react';
import styles from '../styles/Hero.module.css';
import Image from 'next/image';

const Hero = () => {
  return (
    <section className={styles.hero}>
      <div className={styles.heroContent}>
        <div className={styles.heroText}>
          <h1>
            Smart Sentinels
          </h1>
          <p>
            Unlock the Future with Smart Sentinels, where cutting-edge AI technology meets the decentralized world of cryptocurrency. Our AI Agents, running on the powerful Nvidia Jetson Orin Nano Super devices, generate tokens as they work, creating value and opportunities for our community.
          </p>
          <p>
            Become a Stakeholder by minting NFTs from our exclusive collections and share in the rewards generated by our AI Agents. Whether it's Smart Contract audits or advanced AI-driven call centers and tech support, Smart Sentinels is at the forefront of integrating AI and blockchain.
          </p>
          <button className={styles.heroButton}>Learn More</button>
        </div>
        <div className={styles.heroImage}>
          <Image src="/SmartSentinel.png" alt="AI Agent" layout="responsive" width={1200} height={800} />
        </div>
      </div>
    </section>
  );
};

export default Hero;